package sesint3.mapping;


import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author carlos
 */
public class GridMap extends javax.swing.JFrame {
    BufferedImage theMap;
    int imwidth,imheight;
    double scale;
    private String server;
    private int puerto;
            
    public GridMap(int width,int height,double mpp,String server,int puerto){
        imwidth=(int) (width/mpp);
        imheight=(int) (height/mpp);
        scale=mpp;
        theMap=new BufferedImage(imwidth,imheight,BufferedImage.TYPE_INT_ARGB);
        int midgray=(0xff << 24) | (180 << 16) | (180 << 8) | (180);
        
        for(int x=0; x<imwidth; x++){
            for(int y=0; y<imheight; y++){
                theMap.setRGB(x, y, midgray);
            }
        }
        
        this.server=server;
        this.puerto=puerto;
            
        MapPanel mp=new MapPanel();
        add(mp);
    }
    
    void setVal(double x, double y, int value){
        if(value < 0 || value > 255) return;
        
        int imx = (int) (x/scale + imwidth/2);
        int imy = (int) (imheight/2 + y/scale);
        int rgbval= (0xff << 24) | (value << 16) | (value << 8) | (value);
        
        if(imx >=0 && imx < imwidth && imy >=0 && imy < imheight){
            theMap.setRGB(imx,imy,rgbval);
        }
    }
    
    int getVal(double x, double y){
        int value=180;
        
        int imx = (int) (x/scale + imwidth/2);
        int imy = (int) (imheight/2 + y/scale);
        int rgbval= 0;
        
        if(imx >=0 && imx < imwidth && imy >=0 && imy < imheight){
            rgbval =theMap.getRGB(imx, imy);
        }
        
        value=(((rgbval >> 16) & 0x00ff) + ((rgbval >> 8) & 0x0000ff) + (rgbval & 0x000000ff))/3;
        return value;
    }
    
    class MapPanel extends JPanel{
        protected void  paintComponent(Graphics g){            
            g.drawImage(theMap, 0,0, null);
        }
        
        public Dimension getPreferredSize(){
            return new Dimension(imwidth, imheight);
        }
    }
    
    /**
     * Creates new form GridMapForm
     */
    public GridMap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GridMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GridMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GridMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GridMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /*GridMap gridmap=new GridMap(40,40,0.05);
                gridmap.setVisible(true);
                
                Thread thread=new Thread(new Runnable(){
                    @Override
                    public void run() {
                      Mapper mapper=new Mapper(gridmap);
                    }
                    
                });
                
                thread.start();*/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
