/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sesint3;

import java.awt.BorderLayout;
import java.awt.Color;
import javafx.scene.chart.NumberAxis;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;


/**
 *
 * @author carlos
 */
public class FrmRobotMonitor extends javax.swing.JFrame {
    
    //codigo al renderizar la pantalla
    private void init(){
        //generando grafico
        GraficoLineaView graficoLineaView=new GraficoLineaView("Posicion de Robot", "Posicion X", "Posicion Y");
        graficoLineaView.agregarParOrdenado(0.5, 0.5);
        graficoLineaView.agregarParOrdenado(0.8, 0.8);
        graficoLineaView.agregarParOrdenado(2, 2);
        graficoLineaView.agregarParOrdenado(3, 2);
        graficoLineaView.agregarParOrdenado(4, 1);
        graficoLineaView.agregarParOrdenado(5, 0);                
        graficoLineaView.generarGrafico();
        graficoLineaView.setearGraficoEnPanel(canvasPanel);
                                
    }
    
    private void conectarARobots(){        
        String ip= this.txtIP.getText();
        String puerto= this.txtPuerto.getText();
                    
        Thread thread=new Thread(new Runnable(){
            @Override
            public void run() {
                try{                    
                    
                    
                }catch(Exception err){
                    JOptionPane.showMessageDialog(null, "Ingrese IP y puerto valido", "Error del usuario", JOptionPane.ERROR_MESSAGE);
                }
            }
        
        });
        
        thread.start();
    }
    
    /**
     * Creates new form robotMonitor
     */
    public FrmRobotMonitor() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvasPanel = new javax.swing.JPanel();
        btnConectar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIP = new javax.swing.JTextField();
        txtPuerto = new javax.swing.JTextField();
        btnArriba = new javax.swing.JButton();
        btnArriba1 = new javax.swing.JButton();
        btnArriba2 = new javax.swing.JButton();
        btnArriba3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        canvasPanel.setBackground(java.awt.Color.white);
        canvasPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(canvasPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 232, 431, 161));

        btnConectar.setText("Conectar");
        btnConectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConectarMouseClicked(evt);
            }
        });
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 104, -1));

        jLabel1.setText("IP:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 15, -1, -1));

        jLabel2.setText("Puerto:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 50, -1, -1));
        getContentPane().add(txtIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 12, 102, 23));
        getContentPane().add(txtPuerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 47, 102, 23));

        btnArriba.setText("Arriba");
        getContentPane().add(btnArriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 76, 65, -1));

        btnArriba1.setText("Abajo");
        getContentPane().add(btnArriba1, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 150, 65, -1));

        btnArriba2.setText("Derecha");
        getContentPane().add(btnArriba2, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 109, -1, -1));

        btnArriba3.setText("Izquierda");
        getContentPane().add(btnArriba3, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 109, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        conectarARobots();
    }//GEN-LAST:event_btnConectarActionPerformed

    private void btnConectarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConectarMouseClicked
        
    }//GEN-LAST:event_btnConectarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRobotMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRobotMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRobotMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRobotMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRobotMonitor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArriba;
    private javax.swing.JButton btnArriba1;
    private javax.swing.JButton btnArriba2;
    private javax.swing.JButton btnArriba3;
    private javax.swing.JButton btnConectar;
    private javax.swing.JPanel canvasPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtPuerto;
    // End of variables declaration//GEN-END:variables
}
